condition: '{{ true }}'
name: k8s.rules.pod_owner
rules:
- condition: '{{ true }}'
  expr: |-
    max by ({{ .Values.global.clusterLabel }}, namespace, workload, pod) (
      label_replace(
        label_replace(
          kube_pod_owner{job="kube-state-metrics", owner_kind="ReplicaSet"},
          "replicaset", "$1", "owner_name", "(.*)"
        ) * on ({{ .Values.global.clusterLabel }},replicaset, namespace) group_left(owner_name) topk by ({{ .Values.global.clusterLabel }},replicaset, namespace) (
          1, max by ({{ .Values.global.clusterLabel }},replicaset, namespace, owner_name) (
            kube_replicaset_owner{job="kube-state-metrics"}
          )
        ),
        "workload", "$1", "owner_name", "(.*)"
      )
    )
  labels:
    workload_type: deployment
  record: namespace_workload_pod:kube_pod_owner:relabel
- condition: '{{ true }}'
  expr: |-
    max by ({{ .Values.global.clusterLabel }}, namespace, workload, pod) (
      label_replace(
        kube_pod_owner{job="kube-state-metrics", owner_kind="DaemonSet"},
        "workload", "$1", "owner_name", "(.*)"
      )
    )
  labels:
    workload_type: daemonset
  record: namespace_workload_pod:kube_pod_owner:relabel
- condition: '{{ true }}'
  expr: |-
    max by ({{ .Values.global.clusterLabel }}, namespace, workload, pod) (
      label_replace(
        kube_pod_owner{job="kube-state-metrics", owner_kind="StatefulSet"},
        "workload", "$1", "owner_name", "(.*)"
      )
    )
  labels:
    workload_type: statefulset
  record: namespace_workload_pod:kube_pod_owner:relabel
- condition: '{{ true }}'
  expr: |-
    max by ({{ .Values.global.clusterLabel }}, namespace, workload, pod) (
      label_replace(
        kube_pod_owner{job="kube-state-metrics", owner_kind="Job"},
        "workload", "$1", "owner_name", "(.*)"
      )
    )
  labels:
    workload_type: job
  record: namespace_workload_pod:kube_pod_owner:relabel
