condition: '{{ true }}'
name: k8s.rules.container_cpu_usage_seconds_total
rules:
- condition: '{{ true }}'
  expr: |-
    sum by ({{ .Values.global.clusterLabel }}, namespace, pod, container) (
      irate(container_cpu_usage_seconds_total{job="kubelet", metrics_path="/metrics/cadvisor", image!=""}[5m])
    ) * on ({{ .Values.global.clusterLabel }}, namespace, pod) group_left(node) topk by ({{ .Values.global.clusterLabel }}, namespace, pod) (
      1, max by ({{ .Values.global.clusterLabel }}, namespace, pod, node) (kube_pod_info{node!=""})
    )
  record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
